Fix building the iso

diff --git a/scripts/package-installer b/scripts/package-installer
--- a/scripts/package-installer
+++ b/scripts/package-installer
@@ -7,8 +7,9 @@ source ./scripts/version
 
 DOCKERFILE=./scripts/installer/Dockerfile.${ARCH}
 
-if [ ! -e $DOCKERFILE ] || [ ! -e dist/artifacts/vmlinuz ]; then
-    exit 0
+if [ ! -f $DOCKERFILE ] || [ ! -f dist/artifacts/vmlinuz ] || [ ! -f dist/artifacts/initrd ]; then
+    echo "Error: ${DOCKERFILE}, dist/artifacts/vmlinuz or dist/artifacts/initrd is missing"
+    exit 1
 fi
 
 mkdir -p ./scripts/installer/build
